/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  safelist: [
    {
      pattern: /(bg|text|border)-(secondary|tertiary|primary)(\/(5|10))?/,
    },
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#adc6ff",
        "surface-container-low": "#0b1c30",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#dae2fd",
        "inverse-surface": "#d3e4fe",
        "on-primary-fixed": "#131b2e",
        "inverse-primary": "#565e74",
        "on-secondary": "#003824",
        outline: "#909097",
        "tertiary-container": "#00163a",
        "primary-container": "#0f172a",
        error: "#ffb4ab",
        secondary: "#4edea3",
        "on-tertiary-fixed-variant": "#004395",
        "secondary-fixed": "#6ffbbe",
        "inverse-on-surface": "#213145",
        primary: "#bec6e0",
        "on-primary-container": "#798098",
        "on-tertiary-fixed": "#001a42",
        "surface-container": "#102034",
        "on-secondary-fixed": "#002113",
        "on-surface": "#d3e4fe",
        "surface-container-lowest": "#000f21",
        "surface-container-highest": "#26364a",
        "surface-dim": "#031427",
        "surface-bright": "#2a3a4f",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-container": "#00311f",
        "secondary-container": "#00a572",
        "on-error": "#690005",
        "on-tertiary": "#002e6a",
        "primary-fixed-dim": "#bec6e0",
        surface: "#031427",
        "tertiary-fixed": "#d8e2ff",
        "on-surface-variant": "#c6c6cd",
        tertiary: "#adc6ff",
        "on-background": "#d3e4fe",
        "surface-container-high": "#1b2b3f",
        "error-container": "#93000a",
        "outline-variant": "#45464d",
        "on-primary": "#283044",
        "on-secondary-fixed-variant": "#005236",
        background: "#031427",
        "surface-variant": "#26364a",
        "surface-tint": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#357df1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        "section-gap-mobile": "64px",
        "section-gap-desktop": "120px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl": ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
